### ISSUE TITLE
Investigate Problems with Jersey Versions > 2.17

### ISSUE THREAD

**Issue by fwilhe** [osiam/addon-administration#102]
As #101 shows, we have compatibility problems with recent versions of Jersey. We have to fix this in order to be able to update the dependency.

**Comment by dacrome** [comment]
Exception thrown when bump [jersey-client](https://github.com/osiam/addon-administration/blob/4f0bdcbe5d7047fce66a7be2739ddda41bd1111b/pom.xml#L97) to version 2.22.1:
```
2015-10-27 21:42:37.392 ERROR 1900 --- [io-8080-exec-25] o.s.boot.context.web.ErrorPageFilter:
Forwarding to error page from request [/admin/user/edit] due to exception
[org.apache.http.impl.client.HttpClientBuilder.setConnectionManagerShared(Z)Lorg/apache/http/impl/client/HttpClientBuilder;]

java.lang.NoSuchMethodError: org.apache.http.impl.client.HttpClientBuilder.setConnectionManagerShared(Z)Lorg/apache/http/impl/client/HttpClientBuilder;
        at org.glassfish.jersey.apache.connector.ApacheConnector.<init>(ApacheConnector.java:240)
        at org.glassfish.jersey.apache.connector.ApacheConnectorProvider.getConnector(ApacheConnectorProvider.java:115)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:425)
        at org.glassfish.jersey.client.ClientConfig$State.access$000(ClientConfig.java:90)
        at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:122)
        at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:119)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:340)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:733)
        at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
        at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:135)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:105)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:101)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:92)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
        at org.osiam.addons.administration.service.ExtensionsService.requestExtensionTypes(ExtensionsService.java:92)
```
